# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import srpc_pb2 as srpc__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in srpc_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SillyGirlServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.BucketGet = channel.unary_unary(
                '/srpc.SillyGirlService/BucketGet',
                request_serializer=srpc__pb2.BucketKeyRequest.SerializeToString,
                response_deserializer=srpc__pb2.Default.FromString,
                _registered_method=True)
        self.BucketSet = channel.unary_unary(
                '/srpc.SillyGirlService/BucketSet',
                request_serializer=srpc__pb2.BucketSetRequest.SerializeToString,
                response_deserializer=srpc__pb2.BucketSetResponse.FromString,
                _registered_method=True)
        self.BucketDelete = channel.unary_unary(
                '/srpc.SillyGirlService/BucketDelete',
                request_serializer=srpc__pb2.BucketRequest.SerializeToString,
                response_deserializer=srpc__pb2.Empty.FromString,
                _registered_method=True)
        self.BucketKeys = channel.unary_unary(
                '/srpc.SillyGirlService/BucketKeys',
                request_serializer=srpc__pb2.BucketRequest.SerializeToString,
                response_deserializer=srpc__pb2.BucketKeysResponse.FromString,
                _registered_method=True)
        self.BucketLen = channel.unary_unary(
                '/srpc.SillyGirlService/BucketLen',
                request_serializer=srpc__pb2.BucketRequest.SerializeToString,
                response_deserializer=srpc__pb2.LenResponse.FromString,
                _registered_method=True)
        self.BucketGetAll = channel.unary_unary(
                '/srpc.SillyGirlService/BucketGetAll',
                request_serializer=srpc__pb2.BucketRequest.SerializeToString,
                response_deserializer=srpc__pb2.Default.FromString,
                _registered_method=True)
        self.BucketBuckets = channel.unary_unary(
                '/srpc.SillyGirlService/BucketBuckets',
                request_serializer=srpc__pb2.Empty.SerializeToString,
                response_deserializer=srpc__pb2.BucketsResponse.FromString,
                _registered_method=True)
        self.BucketWatch = channel.stream_stream(
                '/srpc.SillyGirlService/BucketWatch',
                request_serializer=srpc__pb2.BucketWatchRequest.SerializeToString,
                response_deserializer=srpc__pb2.BucketWatchResponse.FromString,
                _registered_method=True)
        self.SenderGetUserId = channel.unary_unary(
                '/srpc.SillyGirlService/SenderGetUserId',
                request_serializer=srpc__pb2.SenderRequest.SerializeToString,
                response_deserializer=srpc__pb2.Default.FromString,
                _registered_method=True)
        self.SenderGetUserName = channel.unary_unary(
                '/srpc.SillyGirlService/SenderGetUserName',
                request_serializer=srpc__pb2.SenderRequest.SerializeToString,
                response_deserializer=srpc__pb2.Default.FromString,
                _registered_method=True)
        self.SenderGetChatId = channel.unary_unary(
                '/srpc.SillyGirlService/SenderGetChatId',
                request_serializer=srpc__pb2.SenderRequest.SerializeToString,
                response_deserializer=srpc__pb2.Default.FromString,
                _registered_method=True)
        self.SenderGetChatName = channel.unary_unary(
                '/srpc.SillyGirlService/SenderGetChatName',
                request_serializer=srpc__pb2.SenderRequest.SerializeToString,
                response_deserializer=srpc__pb2.Default.FromString,
                _registered_method=True)
        self.SenderGetMessageId = channel.unary_unary(
                '/srpc.SillyGirlService/SenderGetMessageId',
                request_serializer=srpc__pb2.SenderRequest.SerializeToString,
                response_deserializer=srpc__pb2.Default.FromString,
                _registered_method=True)
        self.SenderIsAdmin = channel.unary_unary(
                '/srpc.SillyGirlService/SenderIsAdmin',
                request_serializer=srpc__pb2.SenderRequest.SerializeToString,
                response_deserializer=srpc__pb2.BoolResponse.FromString,
                _registered_method=True)
        self.SenderGetPlatform = channel.unary_unary(
                '/srpc.SillyGirlService/SenderGetPlatform',
                request_serializer=srpc__pb2.SenderRequest.SerializeToString,
                response_deserializer=srpc__pb2.Default.FromString,
                _registered_method=True)
        self.SenderGetBotId = channel.unary_unary(
                '/srpc.SillyGirlService/SenderGetBotId',
                request_serializer=srpc__pb2.SenderRequest.SerializeToString,
                response_deserializer=srpc__pb2.Default.FromString,
                _registered_method=True)
        self.SenderGetContent = channel.unary_unary(
                '/srpc.SillyGirlService/SenderGetContent',
                request_serializer=srpc__pb2.SenderRequest.SerializeToString,
                response_deserializer=srpc__pb2.Default.FromString,
                _registered_method=True)
        self.SenderSetContent = channel.unary_unary(
                '/srpc.SillyGirlService/SenderSetContent',
                request_serializer=srpc__pb2.SenderContentRequest.SerializeToString,
                response_deserializer=srpc__pb2.Empty.FromString,
                _registered_method=True)
        self.SenderContinue = channel.unary_unary(
                '/srpc.SillyGirlService/SenderContinue',
                request_serializer=srpc__pb2.SenderRequest.SerializeToString,
                response_deserializer=srpc__pb2.Empty.FromString,
                _registered_method=True)
        self.SenderListen = channel.stream_stream(
                '/srpc.SillyGirlService/SenderListen',
                request_serializer=srpc__pb2.SenderListenRequest.SerializeToString,
                response_deserializer=srpc__pb2.SenderListenResponse.FromString,
                _registered_method=True)
        self.SenderEvent = channel.unary_unary(
                '/srpc.SillyGirlService/SenderEvent',
                request_serializer=srpc__pb2.SenderRequest.SerializeToString,
                response_deserializer=srpc__pb2.Default.FromString,
                _registered_method=True)
        self.SenderReply = channel.unary_unary(
                '/srpc.SillyGirlService/SenderReply',
                request_serializer=srpc__pb2.ReplyRequest.SerializeToString,
                response_deserializer=srpc__pb2.Default.FromString,
                _registered_method=True)
        self.SenderParam = channel.unary_unary(
                '/srpc.SillyGirlService/SenderParam',
                request_serializer=srpc__pb2.ReplyRequest.SerializeToString,
                response_deserializer=srpc__pb2.Default.FromString,
                _registered_method=True)
        self.SenderAction = channel.unary_unary(
                '/srpc.SillyGirlService/SenderAction',
                request_serializer=srpc__pb2.ReplyRequest.SerializeToString,
                response_deserializer=srpc__pb2.Default.FromString,
                _registered_method=True)
        self.SenderDestroy = channel.unary_unary(
                '/srpc.SillyGirlService/SenderDestroy',
                request_serializer=srpc__pb2.ReplyRequest.SerializeToString,
                response_deserializer=srpc__pb2.Empty.FromString,
                _registered_method=True)
        self.AdapterRegist = channel.stream_stream(
                '/srpc.SillyGirlService/AdapterRegist',
                request_serializer=srpc__pb2.AdapterRegistRequest.SerializeToString,
                response_deserializer=srpc__pb2.Default.FromString,
                _registered_method=True)
        self.AdapterReceive = channel.unary_unary(
                '/srpc.SillyGirlService/AdapterReceive',
                request_serializer=srpc__pb2.AdapterRequest.SerializeToString,
                response_deserializer=srpc__pb2.Empty.FromString,
                _registered_method=True)
        self.AdapterPush = channel.unary_unary(
                '/srpc.SillyGirlService/AdapterPush',
                request_serializer=srpc__pb2.AdapterRequest.SerializeToString,
                response_deserializer=srpc__pb2.Default.FromString,
                _registered_method=True)
        self.AdapterDestroy = channel.unary_unary(
                '/srpc.SillyGirlService/AdapterDestroy',
                request_serializer=srpc__pb2.AdapterRequest.SerializeToString,
                response_deserializer=srpc__pb2.Empty.FromString,
                _registered_method=True)
        self.AdapterSender = channel.unary_unary(
                '/srpc.SillyGirlService/AdapterSender',
                request_serializer=srpc__pb2.AdapterRequest.SerializeToString,
                response_deserializer=srpc__pb2.Default.FromString,
                _registered_method=True)
        self.Console = channel.unary_unary(
                '/srpc.SillyGirlService/Console',
                request_serializer=srpc__pb2.ConsoleRequest.SerializeToString,
                response_deserializer=srpc__pb2.Empty.FromString,
                _registered_method=True)


class SillyGirlServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def BucketGet(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BucketSet(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BucketDelete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BucketKeys(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BucketLen(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BucketGetAll(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BucketBuckets(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BucketWatch(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SenderGetUserId(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SenderGetUserName(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SenderGetChatId(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SenderGetChatName(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SenderGetMessageId(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SenderIsAdmin(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SenderGetPlatform(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SenderGetBotId(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SenderGetContent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SenderSetContent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SenderContinue(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SenderListen(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SenderEvent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SenderReply(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SenderParam(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SenderAction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SenderDestroy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AdapterRegist(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AdapterReceive(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AdapterPush(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AdapterDestroy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AdapterSender(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Console(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SillyGirlServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'BucketGet': grpc.unary_unary_rpc_method_handler(
                    servicer.BucketGet,
                    request_deserializer=srpc__pb2.BucketKeyRequest.FromString,
                    response_serializer=srpc__pb2.Default.SerializeToString,
            ),
            'BucketSet': grpc.unary_unary_rpc_method_handler(
                    servicer.BucketSet,
                    request_deserializer=srpc__pb2.BucketSetRequest.FromString,
                    response_serializer=srpc__pb2.BucketSetResponse.SerializeToString,
            ),
            'BucketDelete': grpc.unary_unary_rpc_method_handler(
                    servicer.BucketDelete,
                    request_deserializer=srpc__pb2.BucketRequest.FromString,
                    response_serializer=srpc__pb2.Empty.SerializeToString,
            ),
            'BucketKeys': grpc.unary_unary_rpc_method_handler(
                    servicer.BucketKeys,
                    request_deserializer=srpc__pb2.BucketRequest.FromString,
                    response_serializer=srpc__pb2.BucketKeysResponse.SerializeToString,
            ),
            'BucketLen': grpc.unary_unary_rpc_method_handler(
                    servicer.BucketLen,
                    request_deserializer=srpc__pb2.BucketRequest.FromString,
                    response_serializer=srpc__pb2.LenResponse.SerializeToString,
            ),
            'BucketGetAll': grpc.unary_unary_rpc_method_handler(
                    servicer.BucketGetAll,
                    request_deserializer=srpc__pb2.BucketRequest.FromString,
                    response_serializer=srpc__pb2.Default.SerializeToString,
            ),
            'BucketBuckets': grpc.unary_unary_rpc_method_handler(
                    servicer.BucketBuckets,
                    request_deserializer=srpc__pb2.Empty.FromString,
                    response_serializer=srpc__pb2.BucketsResponse.SerializeToString,
            ),
            'BucketWatch': grpc.stream_stream_rpc_method_handler(
                    servicer.BucketWatch,
                    request_deserializer=srpc__pb2.BucketWatchRequest.FromString,
                    response_serializer=srpc__pb2.BucketWatchResponse.SerializeToString,
            ),
            'SenderGetUserId': grpc.unary_unary_rpc_method_handler(
                    servicer.SenderGetUserId,
                    request_deserializer=srpc__pb2.SenderRequest.FromString,
                    response_serializer=srpc__pb2.Default.SerializeToString,
            ),
            'SenderGetUserName': grpc.unary_unary_rpc_method_handler(
                    servicer.SenderGetUserName,
                    request_deserializer=srpc__pb2.SenderRequest.FromString,
                    response_serializer=srpc__pb2.Default.SerializeToString,
            ),
            'SenderGetChatId': grpc.unary_unary_rpc_method_handler(
                    servicer.SenderGetChatId,
                    request_deserializer=srpc__pb2.SenderRequest.FromString,
                    response_serializer=srpc__pb2.Default.SerializeToString,
            ),
            'SenderGetChatName': grpc.unary_unary_rpc_method_handler(
                    servicer.SenderGetChatName,
                    request_deserializer=srpc__pb2.SenderRequest.FromString,
                    response_serializer=srpc__pb2.Default.SerializeToString,
            ),
            'SenderGetMessageId': grpc.unary_unary_rpc_method_handler(
                    servicer.SenderGetMessageId,
                    request_deserializer=srpc__pb2.SenderRequest.FromString,
                    response_serializer=srpc__pb2.Default.SerializeToString,
            ),
            'SenderIsAdmin': grpc.unary_unary_rpc_method_handler(
                    servicer.SenderIsAdmin,
                    request_deserializer=srpc__pb2.SenderRequest.FromString,
                    response_serializer=srpc__pb2.BoolResponse.SerializeToString,
            ),
            'SenderGetPlatform': grpc.unary_unary_rpc_method_handler(
                    servicer.SenderGetPlatform,
                    request_deserializer=srpc__pb2.SenderRequest.FromString,
                    response_serializer=srpc__pb2.Default.SerializeToString,
            ),
            'SenderGetBotId': grpc.unary_unary_rpc_method_handler(
                    servicer.SenderGetBotId,
                    request_deserializer=srpc__pb2.SenderRequest.FromString,
                    response_serializer=srpc__pb2.Default.SerializeToString,
            ),
            'SenderGetContent': grpc.unary_unary_rpc_method_handler(
                    servicer.SenderGetContent,
                    request_deserializer=srpc__pb2.SenderRequest.FromString,
                    response_serializer=srpc__pb2.Default.SerializeToString,
            ),
            'SenderSetContent': grpc.unary_unary_rpc_method_handler(
                    servicer.SenderSetContent,
                    request_deserializer=srpc__pb2.SenderContentRequest.FromString,
                    response_serializer=srpc__pb2.Empty.SerializeToString,
            ),
            'SenderContinue': grpc.unary_unary_rpc_method_handler(
                    servicer.SenderContinue,
                    request_deserializer=srpc__pb2.SenderRequest.FromString,
                    response_serializer=srpc__pb2.Empty.SerializeToString,
            ),
            'SenderListen': grpc.stream_stream_rpc_method_handler(
                    servicer.SenderListen,
                    request_deserializer=srpc__pb2.SenderListenRequest.FromString,
                    response_serializer=srpc__pb2.SenderListenResponse.SerializeToString,
            ),
            'SenderEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.SenderEvent,
                    request_deserializer=srpc__pb2.SenderRequest.FromString,
                    response_serializer=srpc__pb2.Default.SerializeToString,
            ),
            'SenderReply': grpc.unary_unary_rpc_method_handler(
                    servicer.SenderReply,
                    request_deserializer=srpc__pb2.ReplyRequest.FromString,
                    response_serializer=srpc__pb2.Default.SerializeToString,
            ),
            'SenderParam': grpc.unary_unary_rpc_method_handler(
                    servicer.SenderParam,
                    request_deserializer=srpc__pb2.ReplyRequest.FromString,
                    response_serializer=srpc__pb2.Default.SerializeToString,
            ),
            'SenderAction': grpc.unary_unary_rpc_method_handler(
                    servicer.SenderAction,
                    request_deserializer=srpc__pb2.ReplyRequest.FromString,
                    response_serializer=srpc__pb2.Default.SerializeToString,
            ),
            'SenderDestroy': grpc.unary_unary_rpc_method_handler(
                    servicer.SenderDestroy,
                    request_deserializer=srpc__pb2.ReplyRequest.FromString,
                    response_serializer=srpc__pb2.Empty.SerializeToString,
            ),
            'AdapterRegist': grpc.stream_stream_rpc_method_handler(
                    servicer.AdapterRegist,
                    request_deserializer=srpc__pb2.AdapterRegistRequest.FromString,
                    response_serializer=srpc__pb2.Default.SerializeToString,
            ),
            'AdapterReceive': grpc.unary_unary_rpc_method_handler(
                    servicer.AdapterReceive,
                    request_deserializer=srpc__pb2.AdapterRequest.FromString,
                    response_serializer=srpc__pb2.Empty.SerializeToString,
            ),
            'AdapterPush': grpc.unary_unary_rpc_method_handler(
                    servicer.AdapterPush,
                    request_deserializer=srpc__pb2.AdapterRequest.FromString,
                    response_serializer=srpc__pb2.Default.SerializeToString,
            ),
            'AdapterDestroy': grpc.unary_unary_rpc_method_handler(
                    servicer.AdapterDestroy,
                    request_deserializer=srpc__pb2.AdapterRequest.FromString,
                    response_serializer=srpc__pb2.Empty.SerializeToString,
            ),
            'AdapterSender': grpc.unary_unary_rpc_method_handler(
                    servicer.AdapterSender,
                    request_deserializer=srpc__pb2.AdapterRequest.FromString,
                    response_serializer=srpc__pb2.Default.SerializeToString,
            ),
            'Console': grpc.unary_unary_rpc_method_handler(
                    servicer.Console,
                    request_deserializer=srpc__pb2.ConsoleRequest.FromString,
                    response_serializer=srpc__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'srpc.SillyGirlService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('srpc.SillyGirlService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SillyGirlService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def BucketGet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/srpc.SillyGirlService/BucketGet',
            srpc__pb2.BucketKeyRequest.SerializeToString,
            srpc__pb2.Default.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BucketSet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/srpc.SillyGirlService/BucketSet',
            srpc__pb2.BucketSetRequest.SerializeToString,
            srpc__pb2.BucketSetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BucketDelete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/srpc.SillyGirlService/BucketDelete',
            srpc__pb2.BucketRequest.SerializeToString,
            srpc__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BucketKeys(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/srpc.SillyGirlService/BucketKeys',
            srpc__pb2.BucketRequest.SerializeToString,
            srpc__pb2.BucketKeysResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BucketLen(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/srpc.SillyGirlService/BucketLen',
            srpc__pb2.BucketRequest.SerializeToString,
            srpc__pb2.LenResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BucketGetAll(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/srpc.SillyGirlService/BucketGetAll',
            srpc__pb2.BucketRequest.SerializeToString,
            srpc__pb2.Default.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BucketBuckets(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/srpc.SillyGirlService/BucketBuckets',
            srpc__pb2.Empty.SerializeToString,
            srpc__pb2.BucketsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BucketWatch(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/srpc.SillyGirlService/BucketWatch',
            srpc__pb2.BucketWatchRequest.SerializeToString,
            srpc__pb2.BucketWatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SenderGetUserId(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/srpc.SillyGirlService/SenderGetUserId',
            srpc__pb2.SenderRequest.SerializeToString,
            srpc__pb2.Default.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SenderGetUserName(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/srpc.SillyGirlService/SenderGetUserName',
            srpc__pb2.SenderRequest.SerializeToString,
            srpc__pb2.Default.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SenderGetChatId(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/srpc.SillyGirlService/SenderGetChatId',
            srpc__pb2.SenderRequest.SerializeToString,
            srpc__pb2.Default.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SenderGetChatName(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/srpc.SillyGirlService/SenderGetChatName',
            srpc__pb2.SenderRequest.SerializeToString,
            srpc__pb2.Default.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SenderGetMessageId(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/srpc.SillyGirlService/SenderGetMessageId',
            srpc__pb2.SenderRequest.SerializeToString,
            srpc__pb2.Default.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SenderIsAdmin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/srpc.SillyGirlService/SenderIsAdmin',
            srpc__pb2.SenderRequest.SerializeToString,
            srpc__pb2.BoolResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SenderGetPlatform(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/srpc.SillyGirlService/SenderGetPlatform',
            srpc__pb2.SenderRequest.SerializeToString,
            srpc__pb2.Default.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SenderGetBotId(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/srpc.SillyGirlService/SenderGetBotId',
            srpc__pb2.SenderRequest.SerializeToString,
            srpc__pb2.Default.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SenderGetContent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/srpc.SillyGirlService/SenderGetContent',
            srpc__pb2.SenderRequest.SerializeToString,
            srpc__pb2.Default.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SenderSetContent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/srpc.SillyGirlService/SenderSetContent',
            srpc__pb2.SenderContentRequest.SerializeToString,
            srpc__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SenderContinue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/srpc.SillyGirlService/SenderContinue',
            srpc__pb2.SenderRequest.SerializeToString,
            srpc__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SenderListen(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/srpc.SillyGirlService/SenderListen',
            srpc__pb2.SenderListenRequest.SerializeToString,
            srpc__pb2.SenderListenResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SenderEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/srpc.SillyGirlService/SenderEvent',
            srpc__pb2.SenderRequest.SerializeToString,
            srpc__pb2.Default.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SenderReply(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/srpc.SillyGirlService/SenderReply',
            srpc__pb2.ReplyRequest.SerializeToString,
            srpc__pb2.Default.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SenderParam(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/srpc.SillyGirlService/SenderParam',
            srpc__pb2.ReplyRequest.SerializeToString,
            srpc__pb2.Default.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SenderAction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/srpc.SillyGirlService/SenderAction',
            srpc__pb2.ReplyRequest.SerializeToString,
            srpc__pb2.Default.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SenderDestroy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/srpc.SillyGirlService/SenderDestroy',
            srpc__pb2.ReplyRequest.SerializeToString,
            srpc__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AdapterRegist(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/srpc.SillyGirlService/AdapterRegist',
            srpc__pb2.AdapterRegistRequest.SerializeToString,
            srpc__pb2.Default.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AdapterReceive(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/srpc.SillyGirlService/AdapterReceive',
            srpc__pb2.AdapterRequest.SerializeToString,
            srpc__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AdapterPush(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/srpc.SillyGirlService/AdapterPush',
            srpc__pb2.AdapterRequest.SerializeToString,
            srpc__pb2.Default.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AdapterDestroy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/srpc.SillyGirlService/AdapterDestroy',
            srpc__pb2.AdapterRequest.SerializeToString,
            srpc__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AdapterSender(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/srpc.SillyGirlService/AdapterSender',
            srpc__pb2.AdapterRequest.SerializeToString,
            srpc__pb2.Default.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Console(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/srpc.SillyGirlService/Console',
            srpc__pb2.ConsoleRequest.SerializeToString,
            srpc__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
